export const SEARCH_VALUE="SEARCH_VALUE"
export const FETCH_SEARCH_REQUEST = 'FETCH_SEARCH_REQUEST';
export const FETCH_SEARCH_SUCESS = 'FETCH_SEARCH_SUCESS';
export const FETCH_SEARCH_ERROR = 'FETCH_SEARCH_ERROR';